const client = [
    {
        "active": true,
        "id": 12,
        "fullname": "Fábio de Almeida Ribeiro",
        "cpf": "22468050827",
        "rg": "327052983",
        "countrie": "brasil",
        "uf": "sp",
        "city": "São Paulo",
        "cep": "06725105",
        "street": "Av. Inocêncio Píres de Oliveira, 121",
        "phone": "(11) 94005-8153",
        "email": "far820320@gmail.com",
        "password": "$2b$10$U7t2xIQmpkBULHveA6yI8uTcA1zNE7L8cxyu6.nV07ps5qIPfcN6C",
        "file": ""
    },
    {
        "active": true,
        "id": 13,
        "fullname": "Fábio de Almeida Ribeiro",
        "cpf": "22468050827",
        "rg": "327052983",
        "countrie": "brasil",
        "uf": "sp",
        "city": "São Paulo",
        "cep": "06725105",
        "street": "Av. Inocêncio Píres de Oliveira, 121",
        "phone": "(11) 94005-8153",
        "email": "far820320@gmail.com",
        "password": "$2b$10$aH8E2B/EcaaY6j1L17U54up0UhiqGSH0q9gTb9o9c0xtNCpBy4.cG",
        "file": ""
    },
    {
        "active": false,
        "id": 14,
        "fullname": "Fábio de Almeida Ribeiro",
        "cpf": "22468050827",
        "rg": "327052983",
        "countrie": "brasil",
        "uf": "sp",
        "city": "São Paulo",
        "cep": "06725105",
        "street": "Av. Inocêncio Píres de Oliveira, 121",
        "phone": "(11) 94005-8153",
        "email": "far820320@gmail.com",
        "password": "$2b$10$aH8E2B/EcaaY6j1L17U54up0UhiqGSH0q9gTb9o9c0xtNCpBy4.cG",
        "file": ""
    },
    {
        "active": true,
        "id": 17,
        "fullname": "",
        "nickname": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$qFlmdd2J3Te7Rngl36AK7u1jpwssdt9DfGitB7Ti6GBvcM4XANpKS",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 18,
        "fullname": "",
        "nickname": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$Dji/KSdIpEYOmHs5FnksgutUW7eQOJ7f5LQobY1sdgVu6W3TMUP/m",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 19,
        "fullname": "",
        "nickname": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$leHavHlciUP6TTw06vMhc.Ve8BZUv7sW5ocE6RkksYgRK5rVJxdl.",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 20,
        "fullname": "",
        "nickname": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$vBkGVQ7XbtUsChRW2yEEt.J65SwHjWmIDqMswaFreB7lfM1mOmOCy",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 21,
        "fullname": "",
        "nickname": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$PXCzDtvFHvzpCvBGSqniluoaXLDIUPJFuva3vQVKNPuxU4fDdAJdu",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 25,
        "fullname": "",
        "nickname": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$0UU37eyVvjGqWBFZqHkF2.viUUHdcKJPSs2BOdxGXbjP6TzPG2GR6",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 26,
        "fullname": "",
        "nickname": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$3iedRupK3GtVOcatfpGVs.OxwWkDOFNevXOzcwDqloYPI8W.ED7Ea",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 27,
        "fullname": "Fábio de Almeida Ribeiro",
        "nickname": "batata",
        "genre": "male",
        "profession": "sistemasbiomedicos",
        "salary": "der 700000ar 799900",
        "cpf": "",
        "rg": "",
        "cep": "06725105",
        "street": "Av. Inocêncio Píres de Oliveira, 121",
        "city": "São Paulo",
        "uf": "ma",
        "countrie": "uruguai",
        "cnpj": "444444444444444444",
        "company": "Laranja dev br",
        "fantasy": "ibs2",
        "department": "riebiro propaganda",
        "office": "dev",
        "phone": "+5511940058153",
        "email": "far820320@gmail.com",
        "password": "$2b$10$ieDNZNIXCViCa6mr3OopA.nsDJhPqDivma22tZuXAwBoSQdQyKsVa",
        "repeatpassword": "123456"
    },
    {
        "action": true,
        "id": 28,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$8uKGwx.BwZaqe4NWBLs.t./Mpw4oxexjhSmDGoQj8sHRHpjNPyOim",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 29,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$zjOB/LyztHIakj9KCmXI3.9p1m1k/OQzfFvlmk3vXKYRmwgr1CxVS",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 30,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$PjwuZA4Y51qzmlGwDqflc.kqwnnwsty1nt3GMncI788zGfl81IsNy",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 31,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$VgQrNUdcIc5iKQXQ1969pepptAGiINqbXw3LrwhSrZ2XjaODzoOxq",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 32,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$NdzICVLtA/yKW0I5lP4dH.cr0gLzicj9XC7IFYifUI8rMqfoCD5A2",
        "repeatpassword": ""
    },
    {
        "action": true,
        "id": 33,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$K6VxpdHY38KK9qouhqrRSOiCT7pQ5LLgqn9KO3E4m9FGM4qljbw0m",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 34,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$skT76ueFv/2WAN3xvMa/.Ocqmib2u6i6xNCERmTCHAf.zn8HkneZu",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 35,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$FLtaSNJOBklJc3esoWrOkOhkAWdSpkVz4ozRw5EWxYxza4H9eeqxG",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 36,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$KrVtulrsflFw.hJjYrBf6.S0ACI6ZPRKmpwC8sUpLPaBfbsB7teh2",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 37,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$ASPqsgGAmq4u56NNk8br/eCUzStWo24n2PxWlfu/9IpMsoxsqcrTi",
        "repeatpassword": ""
    },
    {
        "active": true,
        "id": 38,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$YbttrgUXMb8fSiW0vs4/X.VE5f.yhkXjKCgdieMn33G/bqi8TGVeG",
        "passagain": ""
    },
    {
        "active": true,
        "id": 39,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$W9edOFBys8B/4.U/9kg0Ku8ER09FNx3QiGc0rhGshD1AMQwNO7tZ.",
        "passagain": ""
    },
    {
        "active": true,
        "id": 40,
        "fullname": "",
        "nickname": "",
        "birthdate": "",
        "biography": "",
        "cpf": "",
        "rg": "",
        "cep": "",
        "street": "",
        "city": "",
        "cnpj": "",
        "company": "",
        "fantasy": "",
        "department": "",
        "office": "",
        "phone": "",
        "email": "",
        "password": "$2b$10$vdsUtu5Bf7QpI0n2PGqWVePDKKeMHFkyAMzkotH2OJDBi5Cnz4c4a",
        "passagain": ""
    }
];module.exports = client;