const elements = [
    {
        active : false,
        label : false,
        log : false,
        name : 'personal data',
        required : false,
        type : 'h3',
    },
    {
        active : true,
        label : true,
        log : false,
        name : 'full name',
        required : false,
        type : 'text',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'cpf',
        required : true,
        type : 'number',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'rg',
        required : true,
        type : 'number',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'adreess',
        required : true,
        type : 'h3',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'street',
        required : true,
        type : 'text',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'number',
        required : true,
        type : 'number',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'neighborhood',
        required : true,
        type : 'text',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'cep',
        required : true,
        type : 'number',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'city',
        required : true,
        type : 'text',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'uf',
        required : true,
        type : 'text',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'phone numbers',
        required : true,
        type : 'h3',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'mobile number',
        required : true,
        type : 'number',
    },
    {
        active : false,
        label : false,
        log : false,
        name : 'commercial number',
        required : true,
        type : 'number',
    },
    {
        active : true,
        label : true,
        log : true,
        name : 'e-mail',
        required : false,
        type : 'email',
    },
    {
        active : true,
        label : true,
        log : true,
        name : 'password',
        required : false,
        type : 'password',
    },
    {
        active : true,
        label : true,
        log : true,
        name : 'checkbox',
        required : false,
        type : 'checkbox',
    },
    {
        active : false,
        label : false,
        log : true,
        name : 'file',
        required : false,
        type : 'h3',
    },
    {
        active : true,
        label : false,
        log : false,
        name : 'file',
        required : false,
        type : 'file',
    },
    {
        active : true,
        label : true,
        log : true,
        name : 'send',
        required : false,
        type : 'submit',
    },
];
module.exports = elements;