const {
    lengths : {
        cep,
        uf,
    },
} = option = require('../options');
const active = true, label = true, placeholder = false, required = false;
module.exports = (disabled) => {
    return [
        {
            active      : active,
            disabled    : disabled,
            label       : label,
            maxlength   : cep,
            name        : 'cep',
            note        : '',
            option      : '',
            placeholder : placeholder,
            required    : required,
            rows        : 0,
            type        : 'text',
            value       : '',
        },
        {
            active      : active,
            disabled    : true,
            label       : label,
            maxlength   : '',
            name        : ['address', 'street'],
            note        : '',
            option      : '',
            placeholder : placeholder,
            required    : required,
            rows        : 0,
            type        : 'text',
            value       : '',
        },
        {
            active      : active,
            disabled    : disabled,
            label       : label,
            maxlength   : '',
            name        : 'number',
            note        : '',
            option      : '',
            placeholder : placeholder,
            required    : required,
            rows        : 0,
            type        : 'number',
            value       : '',
        },
        {
            active      : active,
            disabled    : true,
            label       : label,
            maxlength   : '',
            name        : 'district',
            note        : '',
            option      : '',
            placeholder : placeholder,
            required    : required,
            rows        : 0,
            type        : 'text',
            value       : '',
        },
        {
            active      : active,
            disabled    : true,
            label       : label,
            maxlength   : '',
            name        : 'city',
            note        : '',
            option      : '',
            placeholder : placeholder,
            required    : required,
            rows        : 0,
            type        : 'text',
            value       : '',
        },
        {
            active      : active,
            disabled    : true,
            label       : label,
            maxlength   : uf,
            name        : ['state', 'uf'],
            note        : '',
            option      : '',
            placeholder : placeholder,
            required    : required,
            rows        : 0,
            type        : 'text',
            value       : '',
        },
    ];
};