const firstName = {
    women : [
        'Ana',
        'Beatriz',
        'Carolina',
        'Catarina',
        'Francisca',
        'Leonor',
        'Madalena',
        'Maria',
        'Mariana',
        'Matilde',
    ],
    men : [
        'Afonso',
        'Diogo',
        'Francisco',
        'João',
        'Martim',
        'Miguel',
        'Rodrigo',
        'Santiago',
        'Tiago',
        'Tomás',
    ],
};
const lastName = [
    'Albuquerque',
    'Almeida',
    'Álvares',
    'Alves',
    'Braga',
    'Bragança',
    'Cardoso',
    'Carvalho',
    'Castro',
    'Coimbra',
    'Correia',
    'Costa',
    'da Gama',
    'da Veiga',
    'de Caminha',
    'Fernandes',
    'Ferreira',
    'Fonseca',
    'Gomes',
    'Gonçalves',
    'Guimarães',
    'Henriques',
    'Jesus',
    'Lopes',
    'Marques',
    'Martins',
    'Mendes',
    'Moreira',
    'Nunes',
    'Oliveira',
    'Pereira',
    'Pinto',
    'Ribeiro',
    'Rodrigues',
    'Sampaio',
    'Santos',
    'Silva',
    'Sousa',
    'Teixeira',
    'Vaz',
];
module.exports = {
    firstName : firstName,
    lastName : lastName,
};